### PR TITLE
Bump to 3.42.0

### PR DESCRIPTION
**Pull request by danrabbit**

### CODE REVIEW

**Comment by jeremypw** [comment]
There are some extra spaces introduced into the `json` file.

**Comment by danrabbit** [comment]
@jeremypw fixed!

**Comment by jeremypw** [comment]
The Flatpak builds and runs OK on OS7.  One thing I noticed was that using the "Open .." menu option brings up the unmodified filechooser, not the the elementary one. This chooser did not show other mounted partitions under "Other Locations".  However, this also happened with `main` so not due to this PR.

**Review by jeremypw — APPROVED** [review]

**Comment by danrabbit** [comment]
@jeremypw yeah upstream hasn't migrated to the native filechooser yet because they're using the custom area API from the GTK one

**Pull request merged**
